version: '2'
services:
  base:
    image: $IMAGE_NAME:$IMAGE_TAG
    build:
      context: .
    volumes:
      - $DATALAB:/content/datalab # required, to keep notebooks, docs etc.
      - $DATA:/content/data # to keep corpus data, indexes, models etc.
      - $SSH_CONFIG:/root/.ssh
      - $GITIGNORE_GLOBAL:/root/.gitignore_global
      - .:/content/datalab-nlp
      - ./custom:/custom
    environment:
      #required by Datalab container
      - PROJECT_ID=$PROJECT_ID
      - GOOGLE_CLOUD_PROJECT=$PROJECT_ID # for GCloud SDK
      - DATALAB_ENV=local
      - EXTERNAL_PORT=$EXTERNAL_PORT
      #- DATALAB_DEBUG=true
    entrypoint:
      - /custom/entrypoint.sh
  app:
    extends: base
    ports:
      - $EXTERNAL_PORT:8080
  snorkel:
    extends: base
    working_dir: /snorkel
    entrypoint:
      - /snorkel/docker/entry.sh
    ports:
      - 8888:8888
  snorkel-test:
    extends: base
    working_dir: /snorkel
    entrypoint:
      - /snorkel/docker/test.sh
